/*
 * Copyright (c) 2012-2015, Andrea Funto'. All rights reserved. See LICENSE for details.
 */ 

package org.dihedron.strutlets.exceptions;


/**
 * An exception generated by the framework during the deployment phase, when it 
 * creates the proxy and stub.
 * 
 * @author Andrea Funto'
 */
public class DeploymentException extends StrutletsException {

	/**
	 * Serial version id.
	 */
	private static final long serialVersionUID = -3891772510619458168L;

	/**
	 * Constructor.
	 */
	public DeploymentException() {
	}

	/**
	 * Constructor.
	 *
	 * @param message
	 *   the exception message.
	 */
	public DeploymentException(String message) {
		super(message);
	}

	/**
	 * Constructor.
	 *
	 * @param cause
	 *   the exception's root cause.
	 */
	public DeploymentException(Throwable cause) {
		super(cause);
	}

	/**
	 * Constructor.
	 *
	 * @param message
	 *   the exception's message.
	 * @param cause
	 *   the exception's root cause.
	 */
	public DeploymentException(String message, Throwable cause) {
		super(message, cause);
	}

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}
}
